server_url: "http://localhost:8089"
data_folder: "./data"
plugin_folder: "./plugins"
log_folder: "./data"
epg_filter:
  IsTVChannelFilter: null
  DaysFilter: 7  
  DurationFilter: 70  
  TitleBlacklstFilter: "./data/blacklist.txt"
  KeywordFilter: "Reality-TV,Doku-Soap,Musikshow"  
  ContentMovieFilter: null
  HasTimerFilter: null
timerparameters:
  pre: 5
  post: 5
# if no llm wanted use : null
ai_model: "gpt-5-nano"
ai_provider:
  OPENAI:
    models: gpt-5-mini,gpt-5-nano
    ep: https://api.openai.com/v1
  OLLAMA:
    models: deepseek-r1:latest,qwen3:latest,phi4-mini-reasoning:3.8b
    ep: http://localhost:11434/v1
  OPENROUTER:
    models: deepseek/deepseek-r1-distill-qwen-14b,qwen/qwen3-32b
    ep: https://openrouter.ai/api/v1
  GEMINI:
    models: "gemini-2.5-flash"
    ep: https://generativelanguage.googleapis.com/v1beta/openai/




