# Docker Compose-Datei f체r die FindMovies-Anwendung
#
# Diese Konfiguration vereinfacht das Starten des Containers erheblich.
# Sie verwendet eine .env-Datei im Hauptverzeichnis, um die Pfade zur
# Konfiguration und zu den Datenordnern zu verwalten.
#
# ANLEITUNG:
# 1. Kopieren Sie `docker-compose.env.example` zu `.env`.
# 2. Passen Sie die Pfade in der `.env`-Datei an Ihr System an.
# 3. F체hren Sie `docker-compose up -d` aus.
#
version: '3.8'

services:
  findmovies:
    # Baut das Image aus dem Dockerfile im aktuellen Verzeichnis
    build: .
    image: findmovies-app
    container_name: findmovies-app-instance
    ports:
      - "8000:8000"
    volumes:
      # Mountet die Konfigurations- und Datenordner vom Host-System in den Container.
      # Die Pfade auf dem Host werden 체ber Variablen aus der .env-Datei bezogen.
      - ${CONFIG_PATH}/app.yaml:/app/app.yaml:ro
      - ${DATA_PATH}:/app/data
      - ${PLUGINS_PATH}:/app/plugins
    env_file:
      # L채dt die Umgebungsvariablen (Secrets, LOG_TO_STDOUT) aus der prod.env-Datei.
      - ${CONFIG_PATH}/prod.env
    restart: unless-stopped
